title: Fayyaz Dev Blog
description: >-
  A personal blog about development, technology, and data visualization.
  Exploring tools like Claude Code, AgentStream, and MLFlow.
baseurl: "/fayyazdev-website"
url: "https://tfayyaz.github.io"

# Social links
github_username: tfayyaz

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/